backend:
  name: github
  repo: TaiZeDTich/guitar-songs
  branch: main
  base_url: https://oauth.decapcms.org

media_folder: "images"

collections:
  - name: "songs"
    label: "Песни"
    folder: "songs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Название", name: "title", widget: "string"}
      - {label: "Исполнитель", name: "artist", widget: "string"}
      - {label: "Текст", name: "text", widget: "text"}
